name = "maxapi"
main = "workers/index.js"
compatibility_date = "2024-01-01"

[vars]
# MINIMAX_API_KEY 通过 Cloudflare Dashboard 配置

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[placement]
region = "aws:ap-east-1"
